import React from 'react';
import { Sparkles } from 'lucide-react';

interface AIBadgeProps {
  label?: string;
  className?: string;
}

export function AIBadge({ label = 'AI Generated', className = '' }: AIBadgeProps) {
  return (
    <span
      className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-medium bg-[#FEF3C7] text-[#92400E] border border-[#FCD34D] ${className}`}
      title="This field was generated by AI from the artisan's voice description"
    >
      <Sparkles className="w-3 h-3 text-[#D97706]" aria-hidden="true" />
      <span>✨ {label}</span>
    </span>
  );
}
